name: Make beta artifacts

on:
  push:
    branches:
      - main

jobs:
  make:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable]

        target:
          - x86_64-unknown-linux-gnu
          # - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            use-cross: false

          # - os: ubuntu-20.04
          #   target: aarch64-unknown-linux-gnu
          #   use-cross: true

          - os: macos-latest
            target: x86_64-apple-darwin
            use-cross: false

          - os: macos-11
            target: aarch64-apple-darwin
            use-cross: false

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}

      - name: Install apt dependencies (Ubuntu only)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Handle Rust dependencies caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
          key: v1-${{ matrix.target }}

      - name: Install pnpm dependencies
        run: pnpm install

      # - uses: taiki-e/install-action@cross
      #   if: matrix.use-cross == true

      # - name: Build using cross
      #   if: matrix.use-cross == true
      #   run: |
      #     cd ./src-tauri
      #     cross install tauri-cli
      #     cross tauri build --target ${{ matrix.target }}
      #     cd ../

      - name: Build using pnpm
        if: matrix.use-cross == false
        run: |
          pnpm tauri build --target ${{ matrix.target }} -c ./src-tauri/tauri.beta.conf.json --ci

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        if: matrix.target == 'x86_64-apple-darwin' || matrix.target == 'aarch64-apple-darwin'
        with:
          name: ${{ matrix.target }}
          path: src-tauri/target/${{ matrix.target }}/release/bundle/macos/SolidCord.app
          
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: ${{ matrix.target }}
          path: src-tauri/target/${{ matrix.target }}/release/SolidCord.exe
      
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-20.04'
        with:
          name: ${{ matrix.target }}
          path: src-tauri/target/${{ matrix.target }}/release/bundle/deb/*_amd64.deb
